/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package convertidor_alura;

/**
 *
 * @author alexi
 */
public class Convertidor_AluraL extends javax.swing.JFrame {
    Moneda dolar = new Moneda ("Dolares","USD",18.4);
    Moneda yen = new Moneda ("Yenes","JPY",0.13);
    Moneda euro = new Moneda ("Euros","EUR",19.4);
    Moneda libra = new Moneda ("Libra","GBP",21.97);
    Moneda won = new Moneda ("Won","KRW",0.014);
    Moneda peso = new Moneda ("Pesos","MXN",1);
    Moneda monedas []= {dolar,yen,euro,libra,won,peso};   
    /**
     * Creates new form Convertidor_AluraL
     */
    public Convertidor_AluraL() {
        initComponents();
        for (int i = 0 ;i<monedas.length; i++){
            ls_type1.addItem(monedas [i].getName()+" ("+monedas [i].getAbb()+")");
            ls_type2.addItem(monedas [i].getName()+" ("+monedas [i].getAbb()+")");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ls_type2 = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JLabel();
        ls_type1 = new javax.swing.JComboBox<>();
        in_money = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consultar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Flex", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 139));
        jLabel1.setText("Convertidor Alura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convertidor_alura/images/Vector.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 40, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 139));
        jLabel3.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 139));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 30, 30));

        ls_type2.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jPanel1.add(ls_type2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 160, 30));

        resultado.setBackground(new java.awt.Color(0, 0, 139));
        resultado.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 0, 139));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 270, 30));

        ls_type1.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jPanel1.add(ls_type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, 30));

        in_money.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        in_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_moneyActionPerformed(evt);
            }
        });
        jPanel1.add(in_money, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 139));
        jLabel6.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("a");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 30, 30));

        salir.setBackground(new java.awt.Color(240, 255, 255));
        salir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 128)));
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 128));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Salir");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 20));

        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 40));

        consultar.setBackground(new java.awt.Color(0, 0, 128));
        consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });
        consultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Flex", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Consultar");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        consultar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));

        jPanel1.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_moneyActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        // TODO add your handling code here:
         try{
            double money = Double.parseDouble(in_money.getText());
            if (this.selected_item(ls_type1.getSelectedItem().toString()).equals("Pesos")){
                for (int i = 0; i < monedas.length;i++){
                    if (monedas [i].getName().equals(this.selected_item(ls_type2.getSelectedItem().toString()))){
                        resultado.setText(String.valueOf(monedas [i].convertReverse(Double.parseDouble(in_money.getText()))));
                    }
                }
            }else if (this.selected_item(ls_type2.getSelectedItem().toString()).equals("Pesos")){
                for (int i = 0; i < monedas.length;i++){
                    if (monedas [i].getName().equals(this.selected_item(ls_type1.getSelectedItem().toString()))){
                        resultado.setText(String.valueOf(monedas [i].convertTomxn(Double.parseDouble(in_money.getText()))));
                    }
                }
            }
        }catch(Exception e){
            System.out.print("Fatal error");
            
        }
    }//GEN-LAST:event_consultarMouseClicked
    public String selected_item (String compare){
        String []aux = compare.split (" "); 
        return aux [0];
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor_AluraL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor_AluraL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor_AluraL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor_AluraL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor_AluraL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel consultar;
    private javax.swing.JTextField in_money;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> ls_type1;
    private javax.swing.JComboBox<String> ls_type2;
    private javax.swing.JLabel resultado;
    private javax.swing.JPanel salir;
    // End of variables declaration//GEN-END:variables
}
